# Copyright 2023-2026 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "rs-python"
authors = []
dynamic = ["version"]

requires-python = ">=3.11,<4"

[tool.poetry]
name = "dpr-processor-mockup"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<4"
botocore = "^1.31.83"
boto3 = "^1.28.81"
requests = "^2.31.0"
pyyaml = "^6.0.1"
crcmod = "^1.7"
fastapi = "==0.135.1"
uvicorn = ">=0.35.0"
source = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
pytest-asyncio = "^1.2.0"
pytest-cov = "^7.0.0"
pytest-docker = "^3.2.3"
pytest-error-for-skips = "^2.0.2"
pytest-httpx = ">=0.36"
pytest-mock = "^3.15.1"
moto = { version = "^5.0.1", extras = ["server"] }

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
