import pytest
from http import HTTPStatus
from conftest import PRIP_PRODUCT
import json

# There are like 200k combinations, test list of most used
@pytest.mark.parametrize("url, response", [
    ("/Products?$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=contains(Name, 'IW_RAW__0NSH')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=contains(Name, 'NOT_FOUND')&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'S1A_IW')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=startswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=endswith(Name, 'SAFE.zip')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=endswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and endswith(Name, 'SAFE.zip')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=contains(Name, 'IW_RAW__0NSH') and endswith(Name, 'SAFE.zip')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=startswith(Name, 'INVALID') and endswith(Name, 'SAFE.zip')&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and endswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=EvictionDate eq 9999-12-31T23:59:59.999Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=ModificationDate eq 2022-06-26T06:30:34.558Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=OriginDate eq 2022-06-26T06:14:55.468Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=PublicationDate eq 2022-06-26T06:30:34.558Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Online eq true&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Online invalid_op invalid_value&$expand=Attributes", None),
    ("/Products?$filter=invalid_operator invalid_op invalid_value&$expand=Attributes", None),
    ("/Products?$filter=ContentDate/Start eq 2022-06-26T05:05:33.863Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=ContentDate/End eq 2022-06-26T05:10:38.849Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=OData.CSC.Intersects(area=geography'SRID=4326;POLYGON((-60 0,-62 -10,-58 -10,-56 0,-60 0))')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'polarisationChannels' and att/OData.CSC.StringAttribute/Value eq 'HH')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq 'IW_RAW__0N')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'cycleNumber' and att/OData.CSC.StringAttribute/Value eq '265')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'relativeOrbitNumber' and att/OData.CSC.StringAttribute/Value eq '43829')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingCenter' and att/OData.CSC.StringAttribute/Value eq 'S1 Production Service-SERCO')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'completionTimeFromAscendingNode' and att/OData.CSC.StringAttribute/Value eq '4646455.264')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingDate' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T06:11:22.535Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'datatakeID' and att/OData.CSC.StringAttribute/Value eq '342911')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitNumber' and att/OData.CSC.StringAttribute/Value eq '43829')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productConsolidation' and att/OData.CSC.StringAttribute/Value eq 'FULL')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'endingDateTime' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T05:10:38.849Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'qualityDataObjectID' and att/OData.CSC.StringAttribute/Value eq 'measurementData')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'coordinates' and att/OData.CSC.StringAttribute/Value eq '-59.3169 2.6367,-63.105 -14.0539,-60.8506 -14.4245,-57.13092.3269,-59.3169 2.6367')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitDirection' and att/OData.CSC.StringAttribute/Value eq 'ASCENDING')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'sliceProductFlag' and att/OData.CSC.StringAttribute/Value eq 'False')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'beginningDateTime' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T05:05:33.863Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentConfigurationID' and att/OData.CSC.StringAttribute/Value eq '7')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'startTimeFromAscendingNode' and att/OData.CSC.StringAttribute/Value eq '4341469.328')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentShortName' and att/OData.CSC.StringAttribute/Value eq 'SAR')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productClass' and att/OData.CSC.StringAttribute/Value eq 'N')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformShortName' and att/OData.CSC.StringAttribute/Value eq 'SENTINEL-1')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformSerialIdentifier' and att/OData.CSC.StringAttribute/Value eq 'A')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformShortName' and att/OData.CSC.StringAttribute/Value eq 'SENTINEL-1') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentShortName' and att/OData.CSC.StringAttribute/Value eq 'SAR')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'polarisationChannels' and att/OData.CSC.StringAttribute/Value eq 'HH') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq 'IW_RAW__0N')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'cycleNumber' and att/OData.CSC.StringAttribute/Value eq '265') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitNumber' and att/OData.CSC.StringAttribute/Value eq '43829')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=EvictionDate eq 9999-12-31T23:59:59.999Z and OriginDate eq 2022-06-26T06:14:55.468Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and endswith(Name, 'SAFE.zip')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=ContentDate/Start eq 2022-06-26T05:05:33.863Z and ContentDate/End eq 2022-06-26T05:10:38.849Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'startTimeFromAscendingNode' and att/OData.CSC.StringAttribute/Value eq '4341469.328') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'completionTimeFromAscendingNode' and att/OData.CSC.StringAttribute/Value eq '4646455.264')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'datatakeID' and att/OData.CSC.StringAttribute/Value eq '342911') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingDate' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T06:11:22.535Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitDirection' and att/OData.CSC.StringAttribute/Value eq 'ASCENDING') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productClass' and att/OData.CSC.StringAttribute/Value eq 'N')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformSerialIdentifier' and att/OData.CSC.StringAttribute/Value eq 'A') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingCenter' and att/OData.CSC.StringAttribute/Value eq 'S1 Production Service-SERCO')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=ModificationDate eq 2022-06-26T06:30:34.558Z and PublicationDate eq 2022-06-26T06:30:34.558Z&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productConsolidation' and att/OData.CSC.StringAttribute/Value eq 'FULL') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentConfigurationID' and att/OData.CSC.StringAttribute/Value eq '7')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'qualityDataObjectID' and att/OData.CSC.StringAttribute/Value eq 'measurementData') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'coordinates' and att/OData.CSC.StringAttribute/Value eq '-59.3169 2.6367,-63.105 -14.0539,-60.8506 -14.4245,-57.13092.3269,-59.3169 2.6367')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'sliceProductFlag' and att/OData.CSC.StringAttribute/Value eq 'False') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'endingDateTime' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T05:10:38.849Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'beginningDateTime' and att/OData.CSC.StringAttribute/Value eq '2022-06-26T05:05:33.863Z')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentShortName' and att/OData.CSC.StringAttribute/Value eq 'SAR') and platformShortName eq 'SENTINEL-1'&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'polarisationChannels' and att/OData.CSC.StringAttribute/Value eq 'HH') and orbitNumber eq 43829&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=OData.CSC.Intersects(area=geography'SRID=4326;POLYGON((-60 0,-62 -10,-58 -10,-56 0,-60 0))')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=contains(Name, 'IW_RAW__0NSH') and endswith(Name, 'SAFE.zip')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and ContentDate/End eq 2022-06-26T05:10:38.849Z and orbitDirection eq 'ASCENDING'&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=cycleNumber eq 265 and productType eq 'IW_RAW__0N' and orbitDirection eq 'ASCENDING'&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=instrumentShortName eq 'SAR' and platformShortName eq 'SENTINEL-1' and platformSerialIdentifier eq 'A'&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productClass' and att/OData.CSC.StringAttribute/Value eq 'N') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq 'IW_RAW__0N')&$expand=Attributes", PRIP_PRODUCT),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformShortName' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=endswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=orbitNumber eq 12345 and platformSerialIdentifier eq 'Z'&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentShortName' and att/OData.CSC.StringAttribute/Value eq 'INVALID') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitDirection' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=EvictionDate eq 1900-01-01T00:00:00.000Z&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'polarisationChannels' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'datatakeID' and att/OData.CSC.StringAttribute/Value eq '000000')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'coordinates' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=orbitNumber eq 99999 and cycleNumber eq 999&$expand=Attributes", None),
    ("/Products?$filter=OriginDate eq 2000-01-01T00:00:00.000Z&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'sliceProductFlag' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'instrumentConfigurationID' and att/OData.CSC.StringAttribute/Value eq '999')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'startTimeFromAscendingNode' and att/OData.CSC.StringAttribute/Value eq '9999999')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productClass' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformShortName' and att/OData.CSC.StringAttribute/Value eq 'INVALID') and orbitDirection eq 'INVALID'&$expand=Attributes", None),
    ("/Products?$filter=startswith(Name, 'S1A_IW') and endswith(Name, 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingCenter' and att/OData.CSC.StringAttribute/Value eq 'INVALID') and processingDate eq 2000-01-01T00:00:00.000Z&$expand=Attributes", None),
    ("/Products?$filter=OData.CSC.Intersects(area=geography'SRID=4326;POLYGON((-80 40,-82 30,-78 30,-76 40,-80 40))')&$expand=Attributes", None),
    ("/Products?$filter=contains(Name, 'INVALID') and endswith(Name, 'SAFE.zip')&$expand=Attributes", None),
    ("/Products?$filter=orbitNumber eq 123 and productType eq 'INVALID' and platformSerialIdentifier eq 'Z'&$expand=Attributes", None),
    ("/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'orbitDirection' and att/OData.CSC.StringAttribute/Value eq 'INVALID') and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productConsolidation' and att/OData.CSC.StringAttribute/Value eq 'INVALID')&$expand=Attributes", None),
    ("/Products?$filter=ContentDate/Start eq 2000-01-01T00:00:00.000Z&$expand=Attributes", None),
])
def test_query_products(prip_client, url, response):
    assert prip_client.get(url).status_code == HTTPStatus.OK # Should return all products
    assert json.loads(prip_client.get(url).data)["value"] == ([response] if response else [])