= CADIP server mockup docker image

== Description

This image may be used to start a container that simulates a CADIP server. There are 4 hardcoded files which
are to be sent in the search list and to be downloaded. These files simulate the real name of some chunk raw files from
channels 1 and 2 of S1. Two of them simulate also the final block chunk. +
DCS_04_S1A_20231020064619050845_ch1_DSDB_00001.raw +
DCS_04_S1A_20231121072204051312_ch1_DSDB_00060.raw (final block chunk) +
DCS_04_S1A_20231121072204051312_ch2_DSDB_00046.raw +
DCS_04_S1A_20231121072204051312_ch2_DSDB_00060.raw (final block chunk)

== Building

The docker image may be built with:

```bash
docker build --no-cache --progress=plain -t cadip-server-mockup:<version> .
```

== CLI Docker

The entrypoint of this  docker image is the cadip server mockup, which starts automatically and listens on port 5000. You can use the docker image to run a container as described in this simple example:

```bash
docker run -ti --rm -p 5000:5000/tcp -p 5000:5000/udp cadip-server-mockup:<version>
```

where <version> may be void if the latest will be used.
After you start the container, you will be able to connect a client to it and request the list of files that can be downloaded.
