name: Publish Docker images

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  pre-actions:
    runs-on: ubuntu-latest
    name: "pre-actions"
    outputs:
      sha_short: ${{ steps.pre-actions.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
        # Calculate the short git commit hash
      - id: pre-actions
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  services-adgs-img:
    runs-on: ubuntu-latest
    name: "'services/adgs' Docker image"
    permissions: write-all
    needs: 
      - pre-actions
    outputs:
      docker_image: ${{ steps.publish-docker.outputs.docker_image}}
    steps:
      - uses: actions/checkout@v4

      - id: publish-docker
        uses: ./.github/actions/publish-docker
        with:
          dockerfile: ./src/ADGS/Dockerfile
          build_context_path: ./src/ADGS
          image_suffix: _adgs-station-mock
          version_name: ${{ needs.pre-actions.outputs.sha_short }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  services-cadip-img:
    runs-on: ubuntu-latest
    name: "'services/cadip' Docker image"
    permissions: write-all
    needs: 
      - pre-actions
    outputs:
      docker_image: ${{ steps.publish-docker.outputs.docker_image}}
    steps:
      - uses: actions/checkout@v4

      - id: publish-docker
        uses: ./.github/actions/publish-docker
        with:
          dockerfile: ./src/CADIP/Dockerfile
          build_context_path: ./src/CADIP
          image_suffix: _cadip-station-mock
          version_name: ${{ needs.pre-actions.outputs.sha_short }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

